# \u670D\u52A1\u7AEF\u53E3
server:
  port: 8001

spring:
  application:
    # \u670D\u52A1\u540D
    name: service-city
  # \u73AF\u5883\u8BBE\u7F6E\uFF1Adev\u3001test\u3001prod
  profiles:
    active: dev
  # mysql\u6570\u636E\u5E93\u8FDE\u63A5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel_strategy?characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345
  main:
    allow-bean-definition-overriding: true
  #\u8FD4\u56DEjson\u7684\u5168\u5C40\u65F6\u95F4\u683C\u5F0F
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    loadbalancer:
      retry:
        enabled: true
    nacos:
      discovery:
        # nacos\u670D\u52A1\u5730\u5740
        server-addr: localhost:8848

#\u914D\u7F6Emapper xml\u6587\u4EF6\u7684\u8DEF\u5F84
mybatis-plus:
  mapper-locations: classpath:com/travel/mapper/xml/*.xml