# \u670D\u52A1\u7AEF\u53E3
server:
  port: 8888

# \u670D\u52A1\u540D
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        # nacos\u670D\u52A1\u5730\u5740
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          #\u4F7F\u7528\u670D\u52A1\u53D1\u73B0\u8DEF\u7531
          enabled: true
      routes[0]:
        #\u8BBE\u7F6E\u8DEF\u7531id
        id: service-city
        #\u8BBE\u7F6E\u8DEF\u7531\u7684uri
        uri: lb://service-city
        #\u8BBE\u7F6E\u8DEF\u7531\u65AD\u8A00,\u4EE3\u7406servicerId\u4E3Aauth-service\u7684/auth/\u8DEF\u5F84
        predicates: Path=/*/city/**
      routes[1]:
        id: service-dict
        uri: lb://service-dict
        predicates: Path=/*/dict/**
      routes[2]:
        id: service-user
        uri: lb://service-user
        predicates: Path=/*/user/**
      routes[3]:
        id: service-user
        uri: lb://service-user
        predicates: Path=/images/**